services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_SERVER_URL: http://api:4000
        INTANIA_AUTH_APP_ID: ${INTANIA_AUTH_APP_ID}
        INTANIA_AUTH_SECRET: ${INTANIA_AUTH_SECRET}
        INTANIA_AUTH_REDIRECT_URL: http://localhost:3000/auth
        JWT_SECRET: ${JWT_SECRET}
    restart: always
    depends_on:
      - api
    ports:
      - 3000:3000
    networks:
      - esc_network

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 4000:4000
    networks:
      - esc_network
    env_file:
      - .env

networks:
  esc_network:
    driver: 'bridge'
