services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_SERVER_URL: http://api:4000
    restart: always
    depends_on:
      - api
    ports:
      - 3000:3000
    networks:
      - esc_network
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 4000:4000
    networks:
      - esc_network
    env_file:
      - .env

networks:
  esc_network:
    driver: 'bridge'
