version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 4000:4000
    networks:
      - esc_network

networks:
  esc_network:
    driver: 'bridge'
