//DOCUMENT
export enum FilingStatus {
  APPROVED = 'APPROVED',
  WAIT_FOR_STUDENT_AFFAIR = 'WAIT_FOR_STUDENT_AFFAIR',
  WAIT_FOR_SECRETARY = 'WAIT_FOR_SECRETARY',
  RETURNED = 'RETURNED',
  DRAFT = 'DRAFT',
}

//PROJECT
export enum ProjectStatus {
  CONTINUE = 'CONTINUE',
  WAIT_FOR_CLOSE = 'WAIT_FOR_CLOSE',
  CLOSED = 'CLOSED',
}

export enum ProjectType {
  INTERNAL_AFFAIR = '10',
  ARTS_CULTURE_INTERNAL_AFFAIR = '11',
  ACADEMICS_INTERNAL_AFFAIR = '12',
  SPORTS_INTERNAL_AFFAIR = '13',
  SOCIAL_SERVICE_INTERNAL_AFFAIR = '14',
  NISITSUMPAN_INTERNAL_AFFAIR = '15',
  EXTERNAL_AFFAIR = '20',
  INTERNATIONAL_ACTIVITIES = '30',
  ORGANIZATION_DEVELOPMENT = '40',
  SUPPORT = '50',
  CORPORATE_COMMUNICATION = '60',
  OTHER_ESC = '70',
}
