export enum ObjectiveType {
  KNOWLEDGE_BROAD = 'KNOWLEDGE_BROAD',
  KNOWLEDGE_DEEP = 'KNOWLEDGE_DEEP',
  ETHICS_PROFESSIONALISM = 'ETHICS_PROFESSIONALISM',
  ETHICS_MORALITY = 'ETHICS_MORALITY',
  CRITICAL_THINKING_CREATIVITY = 'CRITICAL_THINKING_CREATIVITY',
  CRITICAL_THINKING_ANALYTICAL = 'CRITICAL_THINKING_ANALYTICAL',
  CRITICAL_THINKING_PROBLEM_SOLVING = 'CRITICAL_THINKING_PROBLEM_SOLVING',
  SKILL_INFORMATION_TECHNOLOGY = 'SKILL_INFORMATION_TECHNOLOGY',
  SKILL_MATH_STATS = 'SKILL_MATH_STATS',
  SKILL_PROFESSIONAL_SKILLS = 'SKILL_PROFESSIONAL_SKILLS',
  SKILL_COMMUNICATION = 'SKILL_COMMUNICATION',
  SKILL_MANAGEMENT = 'SKILL_MANAGEMENT',
  LIFELONG_LEARNING_CURIOSITY = 'LIFELONG_LEARNING_CURIOSITY',
  LIFELONG_LEARNING_METHODS = 'LIFELONG_LEARNING_METHODS',
  LEADERSHIP = 'LEADERSHIP',
  HEALTH_WELLBEING = 'HEALTH_WELLBEING',
  VOLUNTEERISM_PUBLIC_AWARENESS = 'VOLUNTEERISM_PUBLIC_AWARENESS',
  THAI_IDENTITY_GLOBALIZATION = 'THAI_IDENTITY_GLOBALIZATION',
}

export enum ActivityType {
  ACADEMIC_GRADUATE_ATTRIBUTES = 'ACADEMIC_GRADUATE_ATTRIBUTES',
  SPORTS_HEALTH = 'SPORTS_HEALTH',
  VOLUNTEERING_ENVIRONMENT = 'VOLUNTEERING_ENVIRONMENT',
  CULTURAL_ARTS = 'CULTURAL_ARTS',
  ETHICS_MORALITY = 'ETHICS_MORALITY',
}

export enum GraduateAttributeType {
  KNOWLEDGE = 'KNOWLEDGE',
  ETHICS = 'ETHICS',
  CRITICAL_THINKING = 'CRITICAL_THINKING',
  SKILL = 'SKILL',
  LEADERSHIP = 'LEADERSHIP',
  HEALTH = 'HEALTH',
  VOLUNTEER = 'VOLUNTEER',
  THAI_IDENTITY = 'THAI_IDENTITY',
}

export enum ManagementRole {
  ADVISOR = 'ADVISOR',
  PRESIDENT = 'PRESIDENT',
  VICE_PRESIDENT = 'VICE_PRESIDENT',
  SECRETARY = 'SECRETARY',
  TREASURER = 'TREASURER',
  DIVISION_VP = 'DIVISION_VP',
}

export enum SDGType {
  NO_POVERTY = 'NO_POVERTY',
  ZERO_HUNGER = 'ZERO_HUNGER',
  GOOD_HEALTH_AND_WELL_BEING = 'GOOD_HEALTH_AND_WELL_BEING',
  QUALITY_EDUCATION = 'QUALITY_EDUCATION',
  GENDER_EQUALITY = 'GENDER_EQUALITY',
  CLEAN_WATER_AND_SANITATION = 'CLEAN_WATER_AND_SANITATION',
  AFFORDABLE_AND_CLEAN_ENERGY = 'AFFORDABLE_AND_CLEAN_ENERGY',
  DECENT_WORK_AND_ECONOMIC_GROWTH = 'DECENT_WORK_AND_ECONOMIC_GROWTH',
  INDUSTRY_INNOVATION_AND_INFRASTRUCTURE = 'INDUSTRY_INNOVATION_AND_INFRASTRUCTURE',
  REDUCED_INEQUALITIES = 'REDUCED_INEQUALITIES',
  SUSTAINABLE_CITIES_AND_COMMUNITIES = 'SUSTAINABLE_CITIES_AND_COMMUNITIES',
  RESPONSIBLE_CONSUMPTION_AND_PRODUCTION = 'RESPONSIBLE_CONSUMPTION_AND_PRODUCTION',
  CLIMATE_ACTION = 'CLIMATE_ACTION',
  LIFE_BELOW_WATER = 'LIFE_BELOW_WATER',
  LIFE_ON_LAND = 'LIFE_ON_LAND',
  PEACE_JUSTICE_AND_STRONG_INSTITUTIONS = 'PEACE_JUSTICE_AND_STRONG_INSTITUTIONS',
  PARTNERSHIPS_FOR_THE_GOALS = 'PARTNERSHIPS_FOR_THE_GOALS',
}

export enum TQFType {
  ETHICS_AND_MORAL = 'ETHICS_AND_MORAL',
  KNOWLEDGE = 'KNOWLEDGE',
  COGNITIVE_SKILLS = 'COGNITIVE_SKILLS',
  INTERPERSONAL_SKILLS_AND_RESPONSIBILITY = 'INTERPERSONAL_SKILLS_AND_RESPONSIBILITY',
  NUMERICAL_ANALYSIS_COMMUNICATION_AND_INFORMATION_TECHNOLOGY_SKILLS = 'NUMERICAL_ANALYSIS_COMMUNICATION_AND_INFORMATION_TECHNOLOGY_SKILLS',
}

export enum PlanPhase {
  PREPARATION = 'PREPARATION',
  EXECUTION = 'EXECUTION',
  CONCLUSION = 'CONCLUSION',
}
